### PR TITLE
Style wordcamp sponsors blocks

### PR DESCRIPTION
**Pull request by drebbits**
PR for issue https://github.com/wcasia/theme-2020/issues/48.

This are style updates if we create the Sponsors page using the readily available WordCamp Sponsors block. I think this is a much easier way to build the sponsors page given it has available useful block settings.

Page to test:
https://2020.asia.wordcamp.org/?page_id=13349&preview=true

For easy previewing, I recorded my screen:

Desktop:
https://www.dropbox.com/s/4vu5j137mzg7hov/wcasia2020-sponsors-page-01.mov?dl=0

Mobile:
https://www.dropbox.com/s/c86mu8mtktuv98e/wcasia2020-sponsors-page-02.mov?dl=0

Proposing to replace the existing page with this block-driven Sponsors page.

### CODE REVIEW

**Review by tepkenvannkorn — COMMENTED** [review]
I agree with this way to arrange blocks. It's much easier to implement and style. Should we switch to this instead?

**Comment by drebbits** [comment]
@tepkenvannkorn yes. Here's what I think our next steps here:

- [x]  Merge this to master
- [x] Branch off of master to do this changes:

For [In-Kind Sponsors](https://github.com/wcasia/theme-2020/issues/55#issuecomment-557426632):

> we will use Sponsors block moving forward. Use the branch feature/sponsors-blocks instead of master for now to update the In-Kind Sponsors.
> 
>  Update Sticker Mule single sponsor page with the updated text
>  Add In-Kind Sponsor at the bottom in the new Sponsors page (https://2020.asia.wordcamp.org/wp-admin/post.php?post=13349&action=edit) (similar structure as the others: heading and the Sponsors block)
>  Add class has-grid-columns-6 to In-Kind Sponsors block, so we could override the grid count for In-Kind Sponsors to 6 per row (see this diff.
> Can you look into publishing a Sponsor without being added in the current Sponsors page (https://2020.asia.wordcamp.org/sponsors/). This is so we could test adding a sponsor in the In-Kind sponsor.

- [x] Add siam sponsors in the new Sponsors page (sponsors there need to match the Sponsors in the live page https://2020.asia.wordcamp.org/sponsors/)
- [ ] Unpublish the current Sponsors page (rename the permalink slug)
- [ ] Publish the new Sponsors page (rename the permalink slug to `/sponsors/`)

Please let me know if you have any questions.

**Comment by tepkenvannkorn** [comment]
Hey @drebbits, regarding the "Can you look into publishing a Sponsor without being added in the current Sponsors page (https://2020.asia.wordcamp.org/sponsors/). This is so we could test adding a sponsor in the In-Kind sponsor." I could not figure out where the setting is. I decide to skip and start working on styling.

**Comment by drebbits** [comment]
@tepkenvannkorn go ahead proceed with the necessary CSS updates. As a workaround, you can load the Nana sponsors (using the Sponsors block) under the In-Kind section in our new Sponsors page. This is only for testing. The  In-kind should have 6 logos per row (see https://github.com/wcasia/theme-2020/pull/58/files#diff-b6fc2c408b5230cee5457ce1035cc6b4R1639 as an example and use the class name `has-grid-columns-6`)

**Comment by drebbits** [comment]
See the Nana sponsors and under the Advanced settings in its block, I added `has-grid-columns-5` class.

**Comment by tepkenvannkorn** [comment]
Yes, @drebbits it is now done. However, would we need the sideline between each heading?

**Comment by drebbits** [comment]
@tepkenvannkorn that's alright for now, we can actually go with or without sideline since adding a background and making the logos wrap in a rectangle made a very clean alignment

**Comment by drebbits** [comment]
@tepkenvannkorn after previewing the changes in customizer, here are my feedback:

**A.** the sideline doesn't seem to play nicely with the grid especially that it's not align with the left and right edges of the grid. Let's remove that for now if it's going to be a challenge aligning the sideline with the grid.

**B.** reduce the width of the logo images of Silom sponsors. This is what going to separate the Silom from Siam (being Siam sponsors paid more than Silom). In my test, looks like adding width: 60% should work (let's make sure it's center aligned) - but you can definitely suggest another width size.

Screen Shot 2019-11-27 at 3 21 17 PM

**Pull request merged**
