### PR TITLE
Increase logos esp on lower levels like Ari and Nana

### PR DESCRIPTION
**Pull request by drebbits**
Improvements to #48

### CODE REVIEW

**Comment by drebbits** [comment]
Screen Shot 2019-10-24 at 4 09 56 PM

The way I personally test this without deploying yet is overriding the CSS content of the site in Chrome dev tool. 

Copy the wcasia-2020.css into the remote css thru admin-ajax.php:
Screen Shot 2019-10-24 at 4 16 06 PM

That should apply the local changes until you reloads the page.

**Review by appsrex — CHANGES_REQUESTED** [review]
How about we make the design so that logos stand out more? Now it seems like we're promoting the package name with large size text and putting the title on the center( which is okay). But i would still want to see the logo stands out.

**Comment by drebbits** [comment]
@appsrex that's a great feedback, and I do see how it could get disorganized or skewed specially when logos have varying heights. Let's run this feedback by the design team.

**Review by tepkenvannkorn — COMMENTED** [review]
I agree with @appsrex on logo sizes comparing to headings. When sponsorship logo heights vary, how if we follow the Europe layout one? https://2019.europe.wordcamp.org/sponsors/

**Comment by drebbits** [comment]
Great feedback everyone. Given this is a bug on our Sponsors live page now, I will merge this PR. We are working with the design team to improve the overall experience there here based on your feedback - https://github.com/wcasia/theme-2020/issues/48#issuecomment-545841910.

If you have any more comments or you'd like to share feedback, please comment them in the issue #48

**Pull request merged**
